# Generated by Django 4.2.2 on 2024-05-16 23:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(max_length=100, unique=True)),
                ('package_name', models.CharField(max_length=100)),
                ('package_weight', models.FloatField()),
                ('mode_of_transit', models.CharField(choices=[('Air', 'Air'), ('Sea', 'Sea'), ('Road', 'Road')], max_length=10)),
                ('package_status', models.CharField(choices=[('Delivered', 'Delivered'), ('In Transit', 'In Transit')], max_length=20)),
                ('package_date', models.DateTimeField(default=datetime.datetime.now)),
                ('package_location', models.CharField(max_length=100)),
                ('package_destination', models.CharField(max_length=100)),
                ('package_description', models.TextField()),
                ('package_quantity', models.IntegerField()),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('tracking_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consignment.trackingcode')),
            ],
        ),
    ]
