# Generated by Django 4.2.2 on 2024-05-17 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='consignment.customer'),
        ),
        migrations.AddField(
            model_name='package',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='consignment.customer'),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
