# Generated by Django 4.2.2 on 2024-05-17 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0002_package_receiver_package_sender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_location', models.TextField(help_text='Enter the sending location')),
                ('receiving_location', models.TextField(help_text='Enter the receiving location')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consignment.package')),
            ],
        ),
    ]
