# Generated by Django 4.2.2 on 2024-05-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0003_ship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
