# Generated by Django 4.2.2 on 2024-05-18 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0004_alter_package_package_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='package_weight',
        ),
    ]
