# Generated by Django 4.2.2 on 2024-05-18 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0005_remove_package_package_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name_plural': 'Packages'},
        ),
        migrations.AlterModelOptions(
            name='ship',
            options={'verbose_name_plural': 'Ships'},
        ),
        migrations.AlterModelOptions(
            name='trackingcode',
            options={'verbose_name_plural': 'Tracking Codes'},
        ),
        migrations.AddField(
            model_name='package',
            name='package_weight',
            field=models.FloatField(blank=True, default='0.0', null=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consignment.package'),
        ),
    ]
