# Generated by Django 4.2.2 on 2024-05-18 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0006_alter_customer_options_alter_package_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='package',
        ),
        migrations.AddField(
            model_name='package',
            name='receiving_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receive_location', to='consignment.ship'),
        ),
        migrations.AddField(
            model_name='package',
            name='sending_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_location', to='consignment.ship'),
        ),
        migrations.AlterField(
            model_name='package',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='package',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='consignment.customer'),
        ),
        migrations.AlterField(
            model_name='package',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='consignment.customer'),
        ),
    ]
