# Generated by Django 4.2.2 on 2024-05-18 09:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0007_remove_ship_package_package_receiving_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='receiving_location',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Enter the receiving location', null=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='sending_location',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Enter the sending location', null=True),
        ),
    ]
