# Generated by Django 4.2 on 2024-10-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0008_alter_ship_receiving_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude for the map', null=True),
        ),
        migrations.AddField(
            model_name='ship',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude for the map', null=True),
        ),
        migrations.AddField(
            model_name='ship',
            name='map_url',
            field=models.URLField(blank=True, help_text='URL for the iframe map', null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_weight',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
