# Generated by Django 4.2 on 2024-10-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0009_ship_latitude_ship_longitude_ship_map_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='ship',
            name='receiving_location',
            field=models.CharField(blank=True, help_text='Enter the receiving location', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='sending_location',
            field=models.CharField(blank=True, help_text='Enter the sending location', max_length=32, null=True),
        ),
    ]
