# Generated by Django 4.2 on 2024-10-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0011_alter_ship_options_remove_ship_map_url_ship_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='receiving_location',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='sending_location',
        ),
        migrations.AddField(
            model_name='ship',
            name='location',
            field=models.URLField(blank=True, help_text='URL for map iframe', null=True),
        ),
    ]
