# Generated by Django 4.2 on 2024-10-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0012_remove_ship_receiving_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='location',
            field=models.URLField(blank=True, help_text='URL for map iframe', max_length=300, null=True),
        ),
    ]
