# Generated by Django 5.1 on 2024-10-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0013_alter_ship_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='pdf',
        ),
        migrations.AddField(
            model_name='package',
            name='package_image',
            field=models.ImageField(default='default_image.jpg', upload_to='package_images/'),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('On Hold', 'On Hold'), ('In Transit', 'In Transit')], max_length=20),
        ),
    ]
