# Generated by Django 5.1 on 2024-10-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0015_remove_package_package_date_package_delivery_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='location',
            field=models.CharField(blank=True, help_text='name for map iframe', max_length=300, null=True),
        ),
    ]
