# Generated by Django 5.1 on 2024-10-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0016_alter_ship_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='delivery_country',
        ),
        migrations.RemoveField(
            model_name='package',
            name='from_country',
        ),
    ]
