# Generated by Django 5.1 on 2024-10-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0018_package_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='delivery_update',
            field=models.TextField(blank=True, null=True),
        ),
    ]
