# Generated by Django 5.1 on 2024-10-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0019_package_delivery_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
